# A generic, single database configuration.

[alembic]
# This is the URL of your database (adjust as needed)
sqlalchemy.url = postgresql://postgres:9257postgres@localhost:5432/number_db

# The location of migration scripts
script_location = migrations  # Ensure this points to the correct folder (e.g., 'migrations')

# Other Alembic settings, logging, etc.
[loggers]
keys = root,sqlalchemy,alembic,flask_migrate

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[logger_flask_migrate]
level = INFO
handlers =
qualname = flask_migrate

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
